apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polaris-re.fullname" . }}
  labels:
    {{- include "polaris-re.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "polaris-re.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "polaris-re.selectorLabels" . | nindent 8 }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        prometheus.io/path: {{ .Values.metrics.path | quote }}
      {{- end }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - -m
            - uvicorn
            - polaris_re.api.main:app
            - --host
            - "0.0.0.0"
            - --port
            - "8000"
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "polaris-re.fullname" . }}-config
          {{- if .Values.apiKeys }}
          env:
            - name: POLARIS_API_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ include "polaris-re.fullname" . }}-secrets
                  key: api-keys
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
