"""
Analytics engines for Polaris RE — profit testing, scenario analysis, UQ, IFRS 17,
stochastic rates, experience studies, and rate schedule generation.
"""

from polaris_re.analytics.alm import (
    DualDurationGap,
    DurationGapResult,
    DurationMeasures,
    dual_duration_gap,
    duration_gap,
    duration_measures,
    liability_cash_flows,
    reserve_liability_cash_flows,
)
from polaris_re.analytics.capital import CapitalResult, LICATCapital, LICATFactors
from polaris_re.analytics.capital_base import (
    SUPPORTED_CAPITAL_MODELS,
    CapitalModel,
    CapitalModelId,
    CapitalSchedule,
    capital_model_for,
)
from polaris_re.analytics.experience_diligence import (
    AEByYear,
    DiligenceReport,
    EmpiricalBase,
    SoaSurfaceComparison,
    WindowComparison,
    WindowMI,
    attach_empirical_base,
    render_markdown,
    resolve_hmd_paths,
    resolve_ilec_path,
    run_diligence,
)
from polaris_re.analytics.experience_gam import (
    BayesianMISurfaceResult,
    BayesianTensorMIModel,
    ExperienceGAM,
    FittedGLMArrays,
    GAMFitResult,
    HierarchicalMIModel,
    HierarchicalMISurfaceResult,
    MIProjection,
    MISurface,
    MISurfaceResult,
    SmoothEffect,
    TensorMIModel,
    aggregate_seriatim,
    attach_base_rate,
)
from polaris_re.analytics.experience_loaders import (
    default_experience_cache_dir,
    fetch_hmd,
    hmd_1x1_url,
    load_hmd,
    load_ilec,
    parse_hmd_1x1,
)
from polaris_re.analytics.experience_study import AEResult, ExperienceStudy
from polaris_re.analytics.experience_validation import (
    run_experience_improvement_benchmarks,
)
from polaris_re.analytics.ifrs17 import (
    IFRS17Cohort,
    IFRS17CohortManager,
    IFRS17ComponentMovement,
    IFRS17ContractInput,
    IFRS17Measurement,
    IFRS17MovementRow,
    IFRS17MovementTable,
    IFRS17Result,
    build_movement_table,
)
from polaris_re.analytics.perf_harness import (
    PerfDiff,
    PerfProbe,
    PerfReport,
    ProbeDiff,
    default_hot_paths,
    diff_reports,
    output_fingerprint,
    run_perf_probe,
)
from polaris_re.analytics.perf_history import (
    CreepVerdict,
    PerfHistoryRow,
    ProbeCreep,
    ProbeHistoryEntry,
    append_history_row,
    detect_creep,
    load_history,
)
from polaris_re.analytics.portfolio import (
    CacheStats,
    Deal,
    DealResult,
    Portfolio,
    PortfolioResult,
    PortfolioResultWithCapital,
    PortfolioScenarioResult,
)
from polaris_re.analytics.premium_deficiency import (
    PremiumDeficiencyResult,
    PremiumDeficiencyTester,
)
from polaris_re.analytics.premium_sufficiency import (
    PremiumSufficiencyResult,
    PremiumSufficiencyTester,
)
from polaris_re.analytics.pricing import NetPremiumCalculator, NetPremiumResult
from polaris_re.analytics.profit_test import (
    ProfitResultWithCapital,
    ProfitTester,
    ProfitTestResult,
)
from polaris_re.analytics.rate_schedule import SolveMode, YRTRateSchedule
from polaris_re.analytics.rbc import RBCCapital, RBCFactors, RBCResult
from polaris_re.analytics.scale_benchmark import (
    ScaleBenchmarkReport,
    ScaleBenchmarkRow,
    build_homogeneous_block,
    run_scale_benchmark,
)
from polaris_re.analytics.scenario import (
    ScenarioAdjustment,
    ScenarioResult,
    ScenarioRunner,
    apply_scenario_to_assumptions,
)
from polaris_re.analytics.solvency2 import (
    SolvencyIICapital,
    SolvencyIIFactors,
    SolvencyIIResult,
)
from polaris_re.analytics.stochastic import CIRModel, HullWhiteModel, RateScenarios
from polaris_re.analytics.uq import MonteCarloUQ, UQParameters, UQResult
from polaris_re.analytics.validation import (
    ValidationCase,
    ValidationCategory,
    ValidationReport,
    ValidationResult,
    ValidationStatus,
    run_closed_form_benchmarks,
    run_full_validation_pack,
    run_statutory_deck_benchmarks,
)

__all__ = [
    "SUPPORTED_CAPITAL_MODELS",
    "AEByYear",
    "AEResult",
    "BayesianMISurfaceResult",
    "BayesianTensorMIModel",
    "CIRModel",
    "CacheStats",
    "CapitalModel",
    "CapitalModelId",
    "CapitalResult",
    "CapitalSchedule",
    "CreepVerdict",
    "Deal",
    "DealResult",
    "DiligenceReport",
    "DualDurationGap",
    "DurationGapResult",
    "DurationMeasures",
    "EmpiricalBase",
    "ExperienceGAM",
    "ExperienceStudy",
    "FittedGLMArrays",
    "GAMFitResult",
    "HierarchicalMIModel",
    "HierarchicalMISurfaceResult",
    "HullWhiteModel",
    "IFRS17Cohort",
    "IFRS17CohortManager",
    "IFRS17ComponentMovement",
    "IFRS17ContractInput",
    "IFRS17Measurement",
    "IFRS17MovementRow",
    "IFRS17MovementTable",
    "IFRS17Result",
    "LICATCapital",
    "LICATFactors",
    "MIProjection",
    "MISurface",
    "MISurfaceResult",
    "MonteCarloUQ",
    "NetPremiumCalculator",
    "NetPremiumResult",
    "PerfDiff",
    "PerfHistoryRow",
    "PerfProbe",
    "PerfReport",
    "Portfolio",
    "PortfolioResult",
    "PortfolioResultWithCapital",
    "PortfolioScenarioResult",
    "PremiumDeficiencyResult",
    "PremiumDeficiencyTester",
    "PremiumSufficiencyResult",
    "PremiumSufficiencyTester",
    "ProbeCreep",
    "ProbeDiff",
    "ProbeHistoryEntry",
    "ProfitResultWithCapital",
    "ProfitTestResult",
    "ProfitTester",
    "RBCCapital",
    "RBCFactors",
    "RBCResult",
    "RateScenarios",
    "ScaleBenchmarkReport",
    "ScaleBenchmarkRow",
    "ScenarioAdjustment",
    "ScenarioResult",
    "ScenarioRunner",
    "SmoothEffect",
    "SoaSurfaceComparison",
    "SolveMode",
    "SolvencyIICapital",
    "SolvencyIIFactors",
    "SolvencyIIResult",
    "TensorMIModel",
    "UQParameters",
    "UQResult",
    "ValidationCase",
    "ValidationCategory",
    "ValidationReport",
    "ValidationResult",
    "ValidationStatus",
    "WindowComparison",
    "WindowMI",
    "YRTRateSchedule",
    "aggregate_seriatim",
    "append_history_row",
    "apply_scenario_to_assumptions",
    "attach_base_rate",
    "attach_empirical_base",
    "build_homogeneous_block",
    "build_movement_table",
    "capital_model_for",
    "default_experience_cache_dir",
    "default_hot_paths",
    "detect_creep",
    "diff_reports",
    "dual_duration_gap",
    "duration_gap",
    "duration_measures",
    "fetch_hmd",
    "hmd_1x1_url",
    "liability_cash_flows",
    "load_history",
    "load_hmd",
    "load_ilec",
    "output_fingerprint",
    "parse_hmd_1x1",
    "render_markdown",
    "reserve_liability_cash_flows",
    "resolve_hmd_paths",
    "resolve_ilec_path",
    "run_closed_form_benchmarks",
    "run_diligence",
    "run_experience_improvement_benchmarks",
    "run_full_validation_pack",
    "run_perf_probe",
    "run_scale_benchmark",
    "run_statutory_deck_benchmarks",
]
