"""
Excel output formatter for YRT rate schedules.

Produces formatted workbooks matching the layout reinsurers use in practice:
one sheet per sex/smoker combination, age rows, with rate columns.
"""

from pathlib import Path

import polars as pl

__all__ = ["write_rate_schedule_excel"]


def write_rate_schedule_excel(df: pl.DataFrame, path: Path) -> None:
    """
    Write a YRT rate schedule DataFrame to a formatted Excel workbook.

    Creates one sheet per sex/smoker combination. Each sheet has issue_age
    as rows and rate_per_1000 as the value column.

    Args:
        df:   Rate schedule DataFrame from ``YRTRateSchedule.generate()``.
              Expected columns: issue_age, sex, smoker_status, policy_term,
              rate_per_1000, irr.
        path: Output .xlsx file path.

    Raises:
        ImportError: If openpyxl is not installed.
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Font
    except ImportError as exc:
        raise ImportError(
            "openpyxl required for Excel output. Install via: uv sync --extra tables"
        ) from exc

    wb = Workbook()
    # Remove default sheet
    if wb.active is not None:
        wb.remove(wb.active)

    # Group by sex + smoker_status
    groups = df.group_by(["sex", "smoker_status"]).agg(pl.all())

    for row in groups.iter_rows(named=True):
        sex = row["sex"]
        smoker = row["smoker_status"]
        sheet_name = f"{sex}_{smoker}"

        ws = wb.create_sheet(title=sheet_name)

        # Header row
        headers = ["Issue Age", "Policy Term", "Rate per $1,000", "IRR"]
        header_font = Font(bold=True)
        for col_idx, header in enumerate(headers, start=1):
            cell = ws.cell(row=1, column=col_idx, value=header)
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center")

        # Get the ages and rates for this group
        ages = row["issue_age"]
        terms = row["policy_term"]
        rates = row["rate_per_1000"]
        irrs = row["irr"]

        for i in range(len(ages)):
            row_idx = i + 2
            ws.cell(row=row_idx, column=1, value=ages[i])
            ws.cell(row=row_idx, column=2, value=terms[i])

            rate_cell = ws.cell(row=row_idx, column=3, value=rates[i])
            rate_cell.number_format = "0.0000"

            irr_cell = ws.cell(row=row_idx, column=4, value=irrs[i])
            irr_cell.number_format = "0.00%"

        # Auto-width columns
        for col_idx in range(1, 5):
            ws.column_dimensions[chr(64 + col_idx)].width = 16

    # Add summary sheet
    ws_summary = wb.create_sheet(title="Summary", index=0)
    ws_summary.cell(row=1, column=1, value="YRT Rate Schedule Summary").font = Font(
        bold=True, size=14
    )
    ws_summary.cell(row=3, column=1, value="Generated by Polaris RE")
    ws_summary.cell(row=4, column=1, value=f"Total rate cells: {len(df)}")

    if "policy_term" in df.columns:
        terms = df["policy_term"].unique().to_list()
        ws_summary.cell(row=5, column=1, value=f"Policy terms: {terms}")

    wb.save(path)
